export const ON_LOGIN_USERNAME_CHANGED = 'ON_LOGIN_USERNAME_CHANGED';
export const ON_LOGIN_PASSWORD_CHANGED = 'ON_LOGIN_PASSWORD_CHANGED';
export const ON_LOGIN_ATTEMPTED = 'ON_LOGIN_ATTEMPTED';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_LOADING = 'ON_LOGIN_LOADING';
export const ON_LOGIN_STOP_LOADING = 'ON_LOGIN_STOP_LOADING';
export const ON_LOGIN_ATTEMPT_ERROR = 'ON_LOGIN_ATTEMPT_ERROR';