export const ON_APPLICATION_MOUNTED = 'ON_APPLICATION_MOUNTED';
export const ON_INITIALIZE_APPLICATION = 'ON_INITIALIZE_APPLICATION';
export const ON_CHECK_LOCATION_PERMISSION = 'ON_CHECK_LOCATION_PERMISSION';
export const ON_LOCATION_PERMISSION_CHECKED = 'ON_LOCATION_PERMISSION_CHECKED';
export const ON_APPLICATION_SUCCESSFUL_LOGIN_PERSIST_USER = 'ON_APPLICATION_SUCCESSFUL_LOGIN_PERSIST_USER';