export const ON_SIGNUP_INPUT_VALUE_CHANGED = 'ON_SIGNUP_INPUT_VALUE_CHANGED';
export const ON_SIGNUP_ATTEMPTED = 'ON_SIGNUP_ATTEMPTED';
export const ON_SIGNUP_VALIDATION_ERROR = 'ON_SIGNUP_VALIDATION_ERROR';
export const ON_SIGNUP_SUCCESS = 'ON_SIGNUP_SUCCESS';
export const ON_SIGNUP_LOADING = 'ON_SIGNUP_LOADING';
export const ON_SIGNUP_STOP_LOADING = 'ON_SIGNUP_STOP_LOADING';
export const ON_SIGNUP_ATTEMPT_ERROR = 'ON_SIGNUP_ATTEMPT_ERROR';