import {DASHBOARD_DOG_STATUS_FOUND, DASHBOARD_DOG_STATUS_LOST, DASHBOARD_DOG_STATUS_WANDERING} from "./i18n/i18n.keys";

export const USER_ASYNC_STORAGE_KEY = '@USER_ASYNC_STORAGE_KEY';
export const DASHBOARD_NAVIGATION_SCREEN_NAME = 'DASHBOARD_NAVIGATION_SCREEN_NAME';
export const DASHBOARD_LIST_PAGE_SIZE = 10;
export const DASHBOARD_INITIAL_SEARCH_DISTANCE_IN_METERS = 30000;
export const DASHBOARD_MIN_SEARCH_DISTANCE_IN_METERS = 5000;
export const DASHBOARD_MAX_SEARCH_DISTANCE_IN_METERS = 100000;
export const DASHBOARD_STEP_SEARCH_DISTANCE_IN_METERS = 1000;
export const DASHBOARD_INITIAL_SEARCH_TYPE = 0;
export const DASHBOARD_SEARCH_TYPES = {
    [0]: 'LOST',
    [1]: 'FOUND'
};
export const DASHBOARD_DOG_STATUS_ENUM_TRANSLATION_KEYS = {
    'LOST': DASHBOARD_DOG_STATUS_LOST,
    'WANDERING': DASHBOARD_DOG_STATUS_WANDERING,
    'FOUND': DASHBOARD_DOG_STATUS_FOUND
};