export const ON_SUBMIT_FORM_INPUT_VALUE_CHANGED = 'ON_SUBMIT_FORM_INPUT_VALUE_CHANGED';
export const ON_SUBMIT_FORM_SUBMITTED = 'ON_SUBMIT_FORM_SUBMITTED';
export const ON_SUBMIT_FORM_VALIDATION_ERROR = 'ON_SUBMIT_FORM_VALIDATION_ERROR';
export const ON_SUBMIT_FORM_SUCCESS = 'ON_SUBMIT_FORM_SUCCESS';
export const ON_SUBMIT_FORM_LOADING = 'ON_SUBMIT_FORM_LOADING';
export const ON_SUBMIT_FORM_STOP_LOADING = 'ON_SUBMIT_FORM_STOP_LOADING';
export const ON_SUBMIT_FORM_SUBMIT_ERROR = 'ON_SUBMIT_FORM_SUBMIT_ERROR';